--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4
-- Dumped by pg_dump version 14.4

-- Started on 2024-04-21 23:14:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 27865)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    cliente_id bigint NOT NULL,
    direccion character varying(255),
    edad integer NOT NULL,
    genero character varying(255),
    identificacion character varying(255),
    nombre character varying(255),
    telefono character varying(255),
    contrasena character varying(255) NOT NULL,
    estado character varying(255)
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 27864)
-- Name: cliente_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cliente ALTER COLUMN cliente_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 27875)
-- Name: cuenta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuenta (
    id_cuenta bigint NOT NULL,
    estado character varying(255),
    id_cliente bigint,
    numero_cuenta integer,
    saldo_inicial numeric(19,2),
    tipo_cuenta character varying(255)
);


ALTER TABLE public.cuenta OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 27874)
-- Name: cuenta_id_cuenta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuenta ALTER COLUMN id_cuenta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuenta_id_cuenta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 27883)
-- Name: movimiento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimiento (
    id_movimiento bigint NOT NULL,
    fecha timestamp without time zone,
    id_cuenta bigint,
    saldo numeric(19,2),
    saldo_anterior numeric(19,2),
    tipo_movimiento character varying(255),
    valor numeric(19,2)
);


ALTER TABLE public.movimiento OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 27882)
-- Name: movimiento_id_movimiento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimiento ALTER COLUMN id_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_id_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3325 (class 0 OID 27865)
-- Dependencies: 210
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (cliente_id, direccion, edad, genero, identificacion, nombre, telefono, contrasena, estado) FROM stdin;
1	Otavalo sn y principal.	35	Masculino	172069350	Jose Lema	098254785	1234	true
2	Amazonas y  NNUU 	54	Femenino	172069351	Marianela Montalvo	097548965	5678	true
3	Juan Osorio 	28	Masculino	1720693502	Juan Osorio	098874587	1245	true
\.


--
-- TOC entry 3327 (class 0 OID 27875)
-- Dependencies: 212
-- Data for Name: cuenta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuenta (id_cuenta, estado, id_cliente, numero_cuenta, saldo_inicial, tipo_cuenta) FROM stdin;
1	True	1	478758	2000.00	Ahorros
2	True	2	225487	100.00	Corriente
3	True	3	495878	0	Ahorros
4	True	2	496825	540.00	Ahorros
5	True	1	496825	1000.00	Corriente
\.


--
-- TOC entry 3329 (class 0 OID 27883)
-- Dependencies: 214
-- Data for Name: movimiento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimiento (id_movimiento, fecha, id_cuenta, saldo, saldo_anterior, tipo_movimiento, valor) FROM stdin;
1	2024-05-20 09:53:52.52	1	1425.00.00	2000.00	debito	575.00
2	2024-05-20 10:06:36.596	2	700.00	100.00	credito	600.00
3	2024-05-20 10:22:43.48	3	150.00	0.00	credito	150.00
4	2024-05-20 12:07:39.637	4	0.00	540.00	debito	540.00
\.


--
-- TOC entry 3335 (class 0 OID 0)
-- Dependencies: 209
-- Name: cliente_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_cliente_id_seq', 2, true);


--
-- TOC entry 3336 (class 0 OID 0)
-- Dependencies: 211
-- Name: cuenta_id_cuenta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuenta_id_cuenta_seq', 2, true);


--
-- TOC entry 3337 (class 0 OID 0)
-- Dependencies: 213
-- Name: movimiento_id_movimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimiento_id_movimiento_seq', 6, true);


--
-- TOC entry 3175 (class 2606 OID 27871)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (cliente_id);


--
-- TOC entry 3179 (class 2606 OID 27881)
-- Name: cuenta cuenta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_pkey PRIMARY KEY (id_cuenta);


--
-- TOC entry 3183 (class 2606 OID 27887)
-- Name: movimiento movimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimiento
    ADD CONSTRAINT movimiento_pkey PRIMARY KEY (id_movimiento);


--
-- TOC entry 3177 (class 2606 OID 27873)
-- Name: cliente uk_147rikqkb68rxqijmxxgpjwot; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT uk_147rikqkb68rxqijmxxgpjwot UNIQUE (identificacion);


--
-- TOC entry 3181 (class 2606 OID 27889)
-- Name: cuenta uk_pj7ncg765kt4klndu25bwbwe4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT uk_pj7ncg765kt4klndu25bwbwe4 UNIQUE (numero_cuenta);


--
-- TOC entry 3184 (class 2606 OID 27890)
-- Name: movimiento fk8veysyanipny5mpudj13t8873; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimiento
    ADD CONSTRAINT fk8veysyanipny5mpudj13t8873 FOREIGN KEY (id_cuenta) REFERENCES public.cuenta(id_cuenta);


-- Completed on 2024-04-21 23:14:16

--
-- PostgreSQL database dump complete
--

